### ISSUE TITLE
radio input title(tooltip) not shown

### ISSUE THREAD

**Issue by Junker** [arthurgouveia/prettyCheckable#35]
`<input name="style1" title="Style 1" type="radio">`

attribute "title" is not inherited

**Comment by arthurgouveia** [comment]
Indeed. Do you want to fix that? I'm not sure when I'll be able to get my hands on this again.

**Comment by arthurgouveia** [comment]
@Junker do you intend to do this? I'm not sure if that's crucial since you would use a label to add semantic to the input.

I'll close this issue but feel free to open it again if you want to make a PR. You'd need to clone de title attribute from the input and add on the anchor that "replaces" the input.
