### ISSUE TITLE
Disabled-unchecked button images are missing

### ISSUE THREAD

**Issue by aimfeld** [arthurgouveia/prettyCheckable#45]
When I disable radio-buttons and checkboxes, they always show up in a disabled but **checked** status, even if they are unchecked. There seem to be no images for the disabled-unchecked status.

**Comment by arthurgouveia** [comment]
Yeah, indeed there are no images for that or classes to switch the bg position in order to identify if they are checked or not.

It's on the roadmap, so feel free to make a pull request using the provided PSD.

**Comment by bisbell** [comment]
I changed the following line in the CSS to get disabled checkboxes to behave as I expected. Basically, only changing the image for disabled checkboxes to the gray checkmark at -240 if its class is "checked". Then by default the image will be the "open" box for the check box. Did not need to modify any of the images since the open box works for my needs. Thanks.

(original)
.prettycheckbox.disabled a {
  background-position: 0 -240px;
}

(modified)
.prettycheckbox.disabled a.checked {
  background-position: 0 -240px;
}

**Comment by arthurgouveia** [comment]
Hello, guys.

I just pushed a new version of prettyCheckable, which was basically re-written.
Please check the documentation again and do the changes you need. We have these new images you requested and a few other nice features.

Let me know if it solves the issue and please close it.

Thanks!

https://github.com/arthurgouveia/prettyCheckable

**Comment by arthurgouveia** [comment]
In this new version, there are images for both states of the disabled state.
