### ISSUE TITLE
Only available sprite in v2.0 is for blue

### ISSUE THREAD

**Issue by marcusamargi** [arthurgouveia/prettyCheckable#66]
Hello Arthur,

Today I attempted to set my prettyCheckable colors to green and it isn't working. I am using version 2.0. In the sprites directory there is only a sprite for blue. I downloaded and checked version 1.3 and it contained sprites for each of the colors listed in your documentation. Next, I attempted to use a sprite from 1.3 in v2.0, but the older sprite is horizontal while the current version uses vertical.

Am I missing something? How to get green checkboxes to work?
Thanks

**Comment by arthurgouveia** [comment]
Hello, @pymarco!

The 2.0 version came with several changes, one of them being the fact the it's now using Sass and Compass, generating the sprite on the fly.

I've only included the separate pieces for the blue theme, but those can be cut of from the PSD that you can download and you can modify the colors.

Since I was aiming to have users download the minimum amount of files, I've removed the other files for the themes. The sprite is now horizontal because if the sprite was still being downloaded, no matter what state and input you're using, something would be showing up. If it was vertical, depending on what you state and input you were using, it might take longer to show up something.

To get green boxes, you can overwrite the separate files with the green themed ones and Compass will generate your new sprite.

Other ways of doing this is extending the current Sass code adding a class to define with theme it should use, like the previous version or you could simply get the PSD and modify it to your color and orientation of the current generated sprite.

Let me know if I can be of further help.

**Comment by marcusamargi** [comment]
Thanks so much for responding! I'll give it a try
